import {
  Button,
  Checkbox,
  FormControlLabel,
  IconButton,
  Link,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  TextField,
} from '@mui/material'
import { DesktopDatePicker } from '@mui/x-date-pickers'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { Expense } from '../api/expense/types'
import { useCreateExpense } from '../hooks/useCreateExpense'
import { useFindExpenses } from '../hooks/useFindExpenses'
import { useGetCurrentUser } from '../hooks/useGetCurrentUser'
import styles from '../styles/Home.module.css'
import { Delete as DeleteIcon, Edit as EditIcon } from '@mui/icons-material'
import { useDeleteExpense } from '../hooks/useDeleteExpense'

const Home: NextPage = () => {
  const [dateValue, setDateValue] = useState<Date | null>(new Date())
  const { register, handleSubmit, reset } = useForm<Omit<Expense, 'id'>>()
  const { data: currentUser } = useGetCurrentUser()
  const { data: dailyExpenses } = useFindExpenses({
    account_id: currentUser?.id,
    transaction_date: dateValue?.toDateString(),
  })
  const deleteExpense = useDeleteExpense()

  const createExpense = useCreateExpense({
    onSettled: () => {
      reset()
    },
  })

  const dailyExpensesTotal = dailyExpenses
    ? dailyExpenses.reduce((acc, { amount }) => acc + amount, 0) / 100
    : 0

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header>
          {currentUser ? (
            <Image
              alt={`${currentUser.first_name} ${currentUser.last_name}`}
              src={currentUser.avatar}
              width={40}
              height={40}
            />
          ) : (
            <Link
              href={`${process.env.NEXT_PUBLIC_API_HOST}/google?state=${process.env.NEXT_PUBLIC_HOST}`}
            >
              Login
            </Link>
          )}
        </header>
        <DesktopDatePicker
          label="Date"
          inputFormat="MM/dd/yyyy"
          value={dateValue}
          onChange={setDateValue}
          renderInput={(params) => <TextField {...params} />}
        />
        {dailyExpenses && (
          <div>
            <h1>
              Total:{' '}
              {new Intl.NumberFormat('en-US', {
                style: 'currency',
                currency: 'USD',
                minimumFractionDigits: 2,
              }).format(dailyExpensesTotal)}
            </h1>
            <List>
              {dailyExpenses.map((expense) => (
                <ListItem
                  key={expense.id}
                  secondaryAction={
                    <IconButton
                      onClick={() => {
                        if (!currentUser) {
                          return
                        }
                        deleteExpense.mutate({
                          account_id: currentUser.id,
                          id: expense.id,
                        })
                      }}
                      edge="end"
                      aria-label="delete"
                    >
                      <DeleteIcon />
                    </IconButton>
                  }
                >
                  <ListItemIcon>
                    <EditIcon />
                  </ListItemIcon>
                  <ListItemText
                    primary={`${expense.name} - ${new Intl.NumberFormat(
                      'en-US',
                      {
                        style: 'currency',
                        currency: 'USD',
                        minimumFractionDigits: 2,
                      }
                    ).format(expense.amount / 100)}`}
                  />
                </ListItem>
              ))}
            </List>
          </div>
        )}
        <form
          onSubmit={handleSubmit(({ name, amount, recurring }) => {
            if (!currentUser?.id || !dateValue) {
              return
            }

            createExpense.mutate({
              name,
              amount,
              account_id: currentUser.id,
              transaction_date: dateValue.toISOString(),
              recurring,
            })
          })}
        >
          <TextField label="Name" {...register('name')} />
          <TextField label="Amount" {...register('amount')} type="number" />
          <FormControlLabel
            control={<Checkbox {...register('recurring')} />}
            label="Recurring?"
          />
          <Button variant="outlined" type="submit">
            Submit
          </Button>
        </form>
      </main>
    </div>
  )
}

export default Home
